starship config wip

diff --git a/files/zshrc b/files/zshrc
--- a/files/zshrc
+++ b/files/zshrc
@@ -292,19 +292,21 @@ function code() {
 unsetopt HIST_VERIFY
 
 # print exit code once after last command output
-function track-exec-command() {
-  zsh_exec_command=1
-}
-function print-exit-code() {
-  local -i code=$?
-  (( code == 0 )) && return
-  (( zsh_exec_command != 1 )) && return
-  unset zsh_exec_command
-  print -rC1 -- ''${(%):-"%F{160}✘ exit status $code%f"}''
-}
-autoload -Uz add-zsh-hook
-add-zsh-hook preexec track-exec-command
-add-zsh-hook precmd print-exit-code
+#function track-exec-command() {
+#  zsh_exec_command=1
+#}
+#function print-exit-code() {
+#  local -i code=$?
+#  (( code == 0 )) && return
+#  (( zsh_exec_command != 1 )) && return
+#  unset zsh_exec_command
+#  print -rC1 -- ''${(%):-"%F{160}✘ exit status $code%f"}''
+#}
+#autoload -Uz add-zsh-hook
+#add-zsh-hook preexec track-exec-command
+#add-zsh-hook precmd print-exit-code
+
+eval "$(starship init zsh)"
 
 if [ "$ZPROF" ]; then
   zprof
